export const data = [
  {
    letter: "A",
    archetype: [
      [
        "ABC",
        "https://storage.googleapis.com/ygoprodeck.com/pics_artgame/1561110.jpg",
      ],
      [
        "A.I.",
        "https://storage.googleapis.com/ygoprodeck.com/pics_artgame/59332125.jpg",
      ],
      [
        "Albaz",
        "https://storage.googleapis.com/ygoprodeck.com/pics_artgame/68468459.jpg",
      ],
      [
        "Abyss Actor",
        "https://cdn.discordapp.com/attachments/747928182891610213/988314296553467914/abyssactor.webp",
      ],
      [
        "Adamancipator",
        "https://storage.googleapis.com/ygoprodeck.com/pics_artgame/11302671.jpg",
      ],
      [
        "Aesir",
        "https://storage.googleapis.com/ygoprodeck.com/pics_artgame/93483212.jpg",
      ],
      [
        "Alien",
        "https://storage.googleapis.com/ygoprodeck.com/pics_artgame/63253763.jpg",
      ],
      [
        "Allure Queen",
        "https://storage.googleapis.com/ygoprodeck.com/pics_artgame/50140163.jpg",
      ],
      [
        "Ally of Justice",
        "https://storage.googleapis.com/ygoprodeck.com/pics_artgame/26593852.jpg",
      ],

      [
        "Altergeist",
        "https://storage.googleapis.com/ygoprodeck.com/pics_artgame/42790071.jpg",
      ],
      [
        "Amazemment",
        "https://storage.googleapis.com/ygoprodeck.com/pics_artgame/94821366.jpg",
      ],
      [
        "Amazoness",
        "https://storage.googleapis.com/ygoprodeck.com/pics_artgame/15951532.jpg",
      ],
      [
        "Amorphage",
        "https://storage.googleapis.com/ygoprodeck.com/pics_artgame/50554729.jpg",
      ],
      [
        "Ancient Gear",
        "https://storage.googleapis.com/ygoprodeck.com/pics_artgame/95735217.jpg",
      ],
      [
        "Ancient Warriors",
        "https://storage.googleapis.com/ygoprodeck.com/pics_artgame/82791472.jpg",
      ],
      [
        "Appliancer",
        "https://storage.googleapis.com/ygoprodeck.com/pics_artgame/77102944.jpg",
      ],
      [
        "Apoqliphort",
        "https://storage.googleapis.com/ygoprodeck.com/pics_artgame/27279764.jpg",
      ],
      [
        "Aquaactress",
        "https://storage.googleapis.com/ygoprodeck.com/pics_artgame/92053608.jpg",
      ],
      [
        "Arcana Force",
        "https://storage.googleapis.com/ygoprodeck.com/pics_artgame/69831560.jpg",
      ],
      [
        "Archfiend",
        "https://storage.googleapis.com/ygoprodeck.com/pics_artgame/28423537.jpg",
      ],
      [
        "Armed Dragon",
        "https://storage.googleapis.com/ygoprodeck.com/pics_artgame/94141712.jpg",
      ],
      [
        "Aromage",
        "https://storage.googleapis.com/ygoprodeck.com/pics_artgame/58569561.jpg",
      ],
      [
        "Artifact",
        "https://storage.googleapis.com/ygoprodeck.com/pics_artgame/20292186.jpg",
      ],
      [
        "Assault Mode",
        "https://storage.googleapis.com/ygoprodeck.com/pics_artgame/80280737.jpg",
      ],
      [
        "Atlantean",
        "https://storage.googleapis.com/ygoprodeck.com/pics_artgame/47826112.jpg",
      ],
      [
        "Attraction",
        "https://storage.googleapis.com/ygoprodeck.com/pics_artgame/29867611.jpg",
      ],
      [
        "ABC",
        "https://storage.googleapis.com/ygoprodeck.com/pics_artgame/65172015.jpg",
      ],
    ],
  },
  {
    letter: "B",
    archetype: [
      [
        "B.E.S",
        "https://storage.googleapis.com/ygoprodeck.com/pics_artgame/14148099.jpg",
      ],
      [
        "Batteryman",
        "https://storage.googleapis.com/ygoprodeck.com/pics_artgame/19441018.jpg",
      ],
      [
        "Batterguard",
        "https://storage.googleapis.com/ygoprodeck.com/pics_artgame/39389320.jpg",
      ],
      [
        "Battlewasp",
        "https://storage.googleapis.com/ygoprodeck.com/pics_artgame/26443791.jpg",
      ],
      [
        "Battlin' Boxer",
        "https://storage.googleapis.com/ygoprodeck.com/pics_artgame/76589815.jpg",
      ],

      [
        "Beetrooper",
        "https://storage.googleapis.com/ygoprodeck.com/pics_artgame/2834264.jpg",
      ],
      [
        "Black Luster Soldier",
        "https://storage.googleapis.com/ygoprodeck.com/pics_artgame/5405694.jpg",
      ],
      [
        "Blackwing",
        "https://storage.googleapis.com/ygoprodeck.com/pics_artgame/16051717.jpg",
      ],
      [
        "Blue-Eyes",
        "https://storage.googleapis.com/ygoprodeck.com/pics_artgame/89631139.jpg",
      ],
      [
        "Bonding",
        "https://storage.googleapis.com/ygoprodeck.com/pics_artgame/6022371.jpg",
      ],
      [
        "Bounzer",
        "https://storage.googleapis.com/ygoprodeck.com/pics_artgame/92661479.jpg",
      ],
      [
        "Borrel",
        "https://storage.googleapis.com/ygoprodeck.com/pics_artgame/31833038.jpg",
      ],
      [
        "Brave Token",
        "https://storage.googleapis.com/ygoprodeck.com/pics_artgame/30680659.jpg",
      ],
      [
        "Bujin",
        "https://storage.googleapis.com/ygoprodeck.com/pics_artgame/75840616.jpg",
      ],
      [
        "Burning Abyss",
        "https://storage.googleapis.com/ygoprodeck.com/pics_artgame/83531441.jpg",
      ],
      [
        "Butterfly",
        "https://storage.googleapis.com/ygoprodeck.com/pics_artgame/75987257.jpg",
      ],
      [
        "Butterspy",
        "https://storage.googleapis.com/ygoprodeck.com/pics_artgame/79972330.jpg",
      ],
    ],
  },
  {
    letter: "C",
    archetype: [
      [
        "Chaos",
        "https://storage.googleapis.com/ygoprodeck.com/pics_artgame/55878038.jpg",
      ],
      [
        "Chaos Phantom",
        "https://storage.googleapis.com/ygoprodeck.com/pics_artgame/43378048.jpg",
      ],
      [
        "Charmer",
        "https://storage.googleapis.com/ygoprodeck.com/pics_artgame/91530236.jpg",
      ],
      [
        "Chemicritter",
        "https://storage.googleapis.com/ygoprodeck.com/pics_artgame/38026562.jpg",
      ],
      [
        "Chronomaly",
        "https://storage.googleapis.com/ygoprodeck.com/pics_artgame/87430304.jpg",
      ],
      [
        "Chrysalis",
        "https://storage.googleapis.com/ygoprodeck.com/pics_artgame/42682609.jpg",
      ],
      [
        "Cipher",
        "https://storage.googleapis.com/ygoprodeck.com/pics_artgame/29092121.jpg",
      ],
      [
        "Clear Wing",
        "https://storage.googleapis.com/ygoprodeck.com/pics_artgame/82044279.jpg",
      ],
      [
        "Cloudian",
        "https://storage.googleapis.com/ygoprodeck.com/pics_artgame/57610714.jpg",
      ],
      [
        "Code Talker",
        "https://storage.googleapis.com/ygoprodeck.com/pics_artgame/86066372.jpg",
      ],
      [
        "Constellar",
        "https://storage.googleapis.com/ygoprodeck.com/pics_artgame/73964868.jpg",
      ],
      [
        "Crusadia",
        "https://storage.googleapis.com/ygoprodeck.com/pics_artgame/45002991.jpg",
      ],
      [
        "Crystal Beast",
        "https://storage.googleapis.com/ygoprodeck.com/pics_artgame/45002991.jpg",
      ],
      [
        "Crystron",
        "https://storage.googleapis.com/ygoprodeck.com/pics_artgame/20050865.jpg",
      ],
      [
        "Cubic",
        "https://storage.googleapis.com/ygoprodeck.com/pics_artgame/72664875.jpg",
      ],
      [
        "CXyz",
        "https://storage.googleapis.com/ygoprodeck.com/pics_artgame/67926903.jpg",
      ],
      [
        "Cyber Dragon",
        "https://storage.googleapis.com/ygoprodeck.com/pics_artgame/70095154.jpg",
      ],
      [
        "Cyberdark",
        "https://storage.googleapis.com/ygoprodeck.com/pics_artgame/37542782.jpg",
      ],
      [
        "Cyberdark",
        "https://storage.googleapis.com/ygoprodeck.com/pics_artgame/37542782.jpg",
      ],
    ],
  },
  {
    letter: "D",

    archetype: [
      [
        "Danger!",
        "https://storage.googleapis.com/ygoprodeck.com/pics_artgame/43694650.jpg",
      ],
      [
        "Darklord",
        "https://storage.googleapis.com/ygoprodeck.com/pics_artgame/4167084.jpg",
      ],
      [
        "Dark Magician",
        "https://storage.googleapis.com/ygoprodeck.com/pics_artgame/46986414.jpg",
      ],
      [
        "Dark Scorpion",
        "https://storage.googleapis.com/ygoprodeck.com/pics_artgame/20858318.jpg",
      ],
      [
        "Dark World",
        "https://storage.googleapis.com/ygoprodeck.com/pics_artgame/33017655.jpg",
      ],
      [
        "D.D.",
        "https://storage.googleapis.com/ygoprodeck.com/pics_artgame/70074904.jpg",
      ],
      [
        "Deep Sea",
        "https://storage.googleapis.com/ygoprodeck.com/pics_artgame/78868119.jpg",
      ],
      [
        "Deskbot",
        "https://storage.googleapis.com/ygoprodeck.com/pics_artgame/25494711.jpg",
      ],
      [
        "Despia",
        "https://storage.googleapis.com/ygoprodeck.com/pics_artgame/62962630.jpg",
      ],
      [
        "Destiny Hero",
        "https://storage.googleapis.com/ygoprodeck.com/pics_artgame/60461804.jpg",
      ],
      [
        "Destruction Sword",
        "https://storage.googleapis.com/ygoprodeck.com/pics_artgame/78193831.jpg",
      ],
      [
        "Dice",
        "https://storage.googleapis.com/ygoprodeck.com/pics_artgame/83241722.jpg",
      ],
      [
        "Digital Bug",
        "https://storage.googleapis.com/ygoprodeck.com/pics_artgame/85004150.jpg",
      ],
      [
        "Dinomist",
        "https://storage.googleapis.com/ygoprodeck.com/pics_artgame/60675348.jpg",
      ],
      [
        "Dinomorphia",
        "https://storage.googleapis.com/ygoprodeck.com/pics_artgame/78420796.jpg",
      ],
      [
        "Dinowrestler",
        "https://storage.googleapis.com/ygoprodeck.com/pics_artgame/82385847.jpg",
      ],
      [
        "Djinn",
        "https://storage.googleapis.com/ygoprodeck.com/pics_artgame/77153811.jpg",
      ],
      [
        "Dododo",
        "https://storage.googleapis.com/ygoprodeck.com/pics_artgame/39432962.jpg",
      ],
      [
        "Dogmatika",
        "https://storage.googleapis.com/ygoprodeck.com/pics_artgame/60303688.jpg",
      ],
      [
        "Doll",
        "https://storage.googleapis.com/ygoprodeck.com/pics_artgame/72717433.jpg",
      ],
      [
        "Dracoslayer",
        "https://storage.googleapis.com/ygoprodeck.com/pics_artgame/22638495.jpg",
      ],
      [
        "Dracoverlord",
        "https://storage.googleapis.com/ygoprodeck.com/pics_artgame/98287529.jpg",
      ],
      [
        "Dragon Ruler",
        "https://storage.googleapis.com/ygoprodeck.com/pics_artgame/90411554.jpg",
      ],
      [
        "Dragonmaid",
        "https://storage.googleapis.com/ygoprodeck.com/pics_artgame/32600024.jpg",
      ],
      [
        "Dragunity",
        "https://storage.googleapis.com/ygoprodeck.com/pics_artgame/36556781.jpg",
      ],
      [
        "Dream Mirror",
        "https://storage.googleapis.com/ygoprodeck.com/pics_artgame/35187185.jpg",
      ],
      [
        "Drytron",
        "https://storage.googleapis.com/ygoprodeck.com/pics_artgame/1174075.jpg",
      ],
      [
        "Dual Avatar",
        "https://storage.googleapis.com/ygoprodeck.com/pics_artgame/33026283.jpg",
      ],
      [
        "Duston",
        "https://storage.googleapis.com/ygoprodeck.com/pics_artgame/96857854.jpg",
      ],
      [
        "D/D",
        "https://storage.googleapis.com/ygoprodeck.com/pics_artgame/78193831.jpg",
      ],
    ],
  },
  {
    letter: "E",
    archetype: [
      [
        "Earthbound Immortal",
        "https://storage.googleapis.com/ygoprodeck.com/pics_artgame/46263076.jpg",
      ],
      [
        "Edge Imp",
        "https://storage.googleapis.com/ygoprodeck.com/pics_artgame/61173621.jpg",
      ],
      [
        "Eldlich",
        "https://storage.googleapis.com/ygoprodeck.com/pics_artgame/95440947.jpg",
      ],
      [
        "Elemental Hero",
        "https://storage.googleapis.com/ygoprodeck.com/pics_artgame/21844576.jpg",
      ],
      [
        "Elemental Lord",
        "https://storage.googleapis.com/ygoprodeck.com/pics_artgame/13959634.jpg",
      ],
      [
        "Elementsaber",
        "https://storage.googleapis.com/ygoprodeck.com/pics_artgame/45702014.jpg",
      ],
      [
        "Empowered Warrior",
        "https://storage.googleapis.com/ygoprodeck.com/pics_artgame/56681873.jpg",
      ],
      [
        "Endymion",
        "https://storage.googleapis.com/ygoprodeck.com/pics_artgame/65342096.jpg",
      ],
      [
        "Evil Eye",
        "https://storage.googleapis.com/ygoprodeck.com/pics_artgame/29357687.jpg",
      ],
      [
        "Evil Hero",
        "https://storage.googleapis.com/ygoprodeck.com/pics_artgame/13650422.jpg",
      ],
      [
        "Evil★Twin",
        "https://storage.googleapis.com/ygoprodeck.com/pics_artgame/62098216.jpg",
      ],
      [
        "Evilswarm",
        "https://storage.googleapis.com/ygoprodeck.com/pics_artgame/91279700.jpg",
      ],
      [
        "Evolsaur",
        "https://storage.googleapis.com/ygoprodeck.com/pics_artgame/80651316.jpg",
      ],
      [
        "Evoltile",
        "https://storage.googleapis.com/ygoprodeck.com/pics_artgame/81873903.jpg",
      ],
      [
        "Evolzar",
        "https://storage.googleapis.com/ygoprodeck.com/pics_artgame/42752141.jpg",
      ],
      [
        "Exodia",
        "https://storage.googleapis.com/ygoprodeck.com/pics_artgame/33396948.jpg",
      ],
      [
        "Exosister",
        "https://storage.googleapis.com/ygoprodeck.com/pics_artgame/42741437.jpg",
      ],
      [
        "Eyes Restict",
        "https://storage.googleapis.com/ygoprodeck.com/pics_artgame/41578483.jpg",
      ],
    ],
  },
  {
    letter: "S",
    archetype: [
      [
        "Fabled",
        "https://storage.googleapis.com/ygoprodeck.com/pics_artgame/24040093.jpg",
      ],
      [
        "F.A.",
        "https://storage.googleapis.com/ygoprodeck.com/pics_artgame/39271553.jpg",
      ],
      [
        "Fairy Tail",
        "https://storage.googleapis.com/ygoprodeck.com/pics_artgame/55623480.jpg",
      ],
      [
        "Fire-Fist",
        "https://storage.googleapis.com/ygoprodeck.com/pics_artgame/6353603.jpg",
      ],
      [
        "Fire King",
        "https://storage.googleapis.com/ygoprodeck.com/pics_artgame/23015896.jpg",
      ],
      [
        "Fishborg",
        "https://storage.googleapis.com/ygoprodeck.com/pics_artgame/93369354.jpg",
      ],
      [
        "Flamvell",
        "https://storage.googleapis.com/ygoprodeck.com/pics_artgame/53714009.jpg",
      ],
      [
        "Fleur",
        "https://storage.googleapis.com/ygoprodeck.com/pics_artgame/84815190.jpg",
      ],
      [
        "Floowandereeze",
        "https://storage.googleapis.com/ygoprodeck.com/pics_artgame/80611581.jpg",
      ],
      [
        "Flower Cardian",
        "https://storage.googleapis.com/ygoprodeck.com/pics_artgame/33541430.jpg",
      ],
      [
        "Fluffal",
        "https://storage.googleapis.com/ygoprodeck.com/pics_artgame/3841833.jpg",
      ],
      [
        "Fortune Fairy",
        "https://storage.googleapis.com/ygoprodeck.com/pics_artgame/31683874.jpg",
      ],
      [
        "Fortune Lady",
        "https://storage.googleapis.com/ygoprodeck.com/pics_artgame/70252926.jpg",
      ],
      [
        "Fossil",
        "https://storage.googleapis.com/ygoprodeck.com/pics_artgame/96897184.jpg",
      ],
      [
        "Frightfur",
        "https://storage.googleapis.com/ygoprodeck.com/pics_artgame/58468105.jpg",
      ],
      [
        "Frog",
        "https://storage.googleapis.com/ygoprodeck.com/pics_artgame/46239604.jpg",
      ],
      [
        "Fur Hire",
        "https://storage.googleapis.com/ygoprodeck.com/pics_artgame/93850652.jpg",
      ],
    ],
  },
  {
    letter: "G",
    archetype: [
      [
        "Gadget",
        "https://storage.googleapis.com/ygoprodeck.com/pics_artgame/55010259.jpg",
      ],
      [
        "Gagaga",
        "https://storage.googleapis.com/ygoprodeck.com/pics_artgame/12014404.jpg",
      ],
      [
        "Gaia The Fierce Knight",
        "https://storage.googleapis.com/ygoprodeck.com/pics_artgame/91949988.jpg",
      ],
      [
        "Galaxy",
        "https://storage.googleapis.com/ygoprodeck.com/pics_artgame/18963306.jpg",
      ],
      [
        "Galaxy-Eyes",
        "https://storage.googleapis.com/ygoprodeck.com/pics_artgame/62968263.jpg",
      ],
      [
        "Gandora",
        "https://storage.googleapis.com/ygoprodeck.com/pics_artgame/64681432.jpg",
      ],
      [
        "Geargia",
        "https://storage.googleapis.com/ygoprodeck.com/pics_artgame/19891310.jpg",
      ],
      [
        "Gem-",
        "https://storage.googleapis.com/ygoprodeck.com/pics_artgame/19355597.jpg",
      ],
      [
        "Generaider",
        "https://storage.googleapis.com/ygoprodeck.com/pics_artgame/68199168.jpg",
      ],
      [
        "Genex",
        "https://storage.googleapis.com/ygoprodeck.com/pics_artgame/68505803.jpg",
      ],
      [
        "Ghostrick",
        "https://storage.googleapis.com/ygoprodeck.com/pics_artgame/75367227.jpg",
      ],
      [
        "Gimmick Puppet",
        "https://storage.googleapis.com/ygoprodeck.com/pics_artgame/79086452.jpg",
      ],
      [
        "Gishki",
        "https://storage.googleapis.com/ygoprodeck.com/pics_artgame/66729231.jpg",
      ],
      [
        "Gizmek",
        "https://storage.googleapis.com/ygoprodeck.com/pics_artgame/63633694.jpg",
      ],
      [
        "Glacial Beast",
        "https://storage.googleapis.com/ygoprodeck.com/pics_artgame/6568731.jpg",
      ],
      [
        "Gladiator Beast",
        "https://storage.googleapis.com/ygoprodeck.com/pics_artgame/33652635.jpg",
      ],
      [
        "Gogogo",
        "https://storage.googleapis.com/ygoprodeck.com/pics/59724555.jpg",
      ],
      [
        "Gorgonic",
        "https://storage.googleapis.com/ygoprodeck.com/pics_artgame/84401683.jpg",
      ],
      [
        "Gouki",
        "https://storage.googleapis.com/ygoprodeck.com/pics_artgame/30286474.jpg",
      ],
      [
        "Gravekeeper",
        "https://storage.googleapis.com/ygoprodeck.com/pics_artgame/25524823.jpg",
      ],
      [
        "Graydle",
        "https://storage.googleapis.com/ygoprodeck.com/pics_artgame/52145422.jpg",
      ],
      [
        "Grepher",
        "https://storage.googleapis.com/ygoprodeck.com/pics_artgame/27407330.jpg",
      ],
      [
        "Gunkan",
        "https://storage.googleapis.com/ygoprodeck.com/pics_artgame/61027400.jpg",
      ],
      [
        "Gusto",
        "https://storage.googleapis.com/ygoprodeck.com/pics_artgame/29552709.jpg",
      ],
    ],
  },
  {
    letter: "H",
    archetype: [
      [
        "Harpie",
        "https://storage.googleapis.com/ygoprodeck.com/pics_artgame/63261835.jpg",
      ],
      [
        "Hazy Flame",
        "https://storage.googleapis.com/ygoprodeck.com/pics_artgame/1409474.jpg",
      ],
      [
        "Heraldic Beast",
        "https://storage.googleapis.com/ygoprodeck.com/pics_artgame/45705025.jpg",
      ],
      [
        "Heroic",
        "https://storage.googleapis.com/ygoprodeck.com/pics_artgame/63504681.jpg",
      ],
      [
        "Hieratic",
        "https://storage.googleapis.com/ygoprodeck.com/pics_artgame/78033100.jpg",
      ],
      [
        "Hole",
        "https://storage.googleapis.com/ygoprodeck.com/pics_artgame/11593137.jpg",
      ],
      [
        "Horus the Black Flame Dragon",
        "https://storage.googleapis.com/ygoprodeck.com/pics_artgame/48229808.jpg",
      ],
      [
        "Hyperion",
        "https://storage.googleapis.com/ygoprodeck.com/pics_artgame/91434602.jpg",
      ],
    ],
  },
  {
    letter: "I",
    archetype: [
      [
        "Ice Barrier",
        "https://storage.googleapis.com/ygoprodeck.com/pics_artgame/60161788.jpg",
      ],
      [
        "Icejade",
        "https://storage.googleapis.com/ygoprodeck.com/pics_artgame/3355732.jpg",
      ],
      [
        "Igknight",
        "https://storage.googleapis.com/ygoprodeck.com/pics_artgame/65872270.jpg",
      ],
      [
        "@Ignister",
        "https://storage.googleapis.com/ygoprodeck.com/pics_artgame/11738489.jpg",
      ],
      [
        "Impcantation",
        "https://storage.googleapis.com/ygoprodeck.com/pics_artgame/65877963.jpg",
      ],
      [
        "Infernity",
        "https://storage.googleapis.com/ygoprodeck.com/pics_artgame/85475641.jpg",
      ],
      [
        "Infernoid",
        "https://storage.googleapis.com/ygoprodeck.com/pics_artgame/82734805.jpg",
      ],
      [
        "Infestation",
        "https://storage.googleapis.com/ygoprodeck.com/pics_artgame/35419032.jpg",
      ],
      [
        "Infinitrack",
        "https://storage.googleapis.com/ygoprodeck.com/pics_artgame/97316367.jpg",
      ],
      [
        "Invoked",
        "https://storage.googleapis.com/ygoprodeck.com/pics_artgame/75286621.jpg",
      ],
      [
        "Inzektor",
        "https://storage.googleapis.com/ygoprodeck.com/pics_artgame/38450736.jpg",
      ],
      [
        "Iron Chain",
        "https://storage.googleapis.com/ygoprodeck.com/pics_artgame/19974580.jpg",
      ],
    ],
  },
  {
    letter: "J",
    archetype: [
      [
        "Jester",
        "https://storage.googleapis.com/ygoprodeck.com/pics_artgame/72992744.jpg",
      ],
      [
        "Jinzo",
        "https://storage.googleapis.com/ygoprodeck.com/pics_artgame/77585514.jpg",
      ],
      [
        "Junk",
        "https://storage.googleapis.com/ygoprodeck.com/pics_artgame/60800381.jpg",
      ],
      [
        "Jurrac",
        "https://storage.googleapis.com/ygoprodeck.com/pics_artgame/80032567.jpg",
      ],
    ],
  },
  {
    letter: "k",
    archetype: [
      [
        "Kaiju",
        "https://storage.googleapis.com/ygoprodeck.com/pics_artgame/55063751.jpg",
      ],
      [
        "Karakuri",
        "https://storage.googleapis.com/ygoprodeck.com/pics_artgame/25904894.jpg",
      ],
      [
        "Knightmare",
        "https://storage.googleapis.com/ygoprodeck.com/pics_artgame/38342336.jpg",
      ],
      [
        "Koa'ki Meiru",
        "https://storage.googleapis.com/ygoprodeck.com/pics_artgame/65026212.jpg",
      ],
      [
        "Koala",
        "https://storage.googleapis.com/ygoprodeck.com/pics_artgame/42129512.jpg",
      ],
      [
        "Kozmo",
        "https://storage.googleapis.com/ygoprodeck.com/pics_artgame/31061682.jpg",
      ],
      [
        "Krawler",
        "https://storage.googleapis.com/ygoprodeck.com/pics_artgame/39998992.jpg",
      ],
      [
        "Kshatri-La",
        "https://storage.googleapis.com/ygoprodeck.com/pics_artgame/101110013.jpg",
      ],
      [
        "Kuriboh",
        "https://storage.googleapis.com/ygoprodeck.com/pics_artgame/40640059.jpg",
      ],
    ],
  },
  {
    letter: "L",
    archetype: [
      [
        "Labrynth",
        "https://storage.googleapis.com/ygoprodeck.com/pics_artgame/2347656.jpg",
      ],
      [
        "Laval",
        "https://storage.googleapis.com/ygoprodeck.com/pics_artgame/8041569.jpg",
      ],
      [
        "Legendary Knight",
        "https://storage.googleapis.com/ygoprodeck.com/pics_artgame/84565800.jpg",
      ],
      [
        "Libromancer",
        "https://storage.googleapis.com/ygoprodeck.com/pics_artgame/46123974.jpg",
      ],
      [
        "Lightsworn",
        "https://storage.googleapis.com/ygoprodeck.com/pics_artgame/30100551.jpg",
      ],
      [
        "Lunalight",
        "https://storage.googleapis.com/ygoprodeck.com/pics_artgame/88753594.jpg",
      ],
      [
        "Lyrilusc",
        "https://storage.googleapis.com/ygoprodeck.com/pics_artgame/48608796.jpg",
      ],
    ],
  },
  {
    letter: "M",
    archetype: [
      [
        "Machina",
        "https://storage.googleapis.com/ygoprodeck.com/pics_artgame/87074380.jpg",
      ],
      [
        "Madolche",
        "https://storage.googleapis.com/ygoprodeck.com/pics_artgame/44311445.jpg",
      ],
      [
        "Magical Musket",
        "https://storage.googleapis.com/ygoprodeck.com/pics_artgame/71791814.jpg",
      ],
      [
        "Magikey",
        "https://storage.googleapis.com/ygoprodeck.com/pics_artgame/98234196.jpg",
      ],
      [
        "Magistus",
        "https://storage.googleapis.com/ygoprodeck.com/pics_artgame/34755994.jpg",
      ],
      [
        "Magnet Warrior",
        "https://storage.googleapis.com/ygoprodeck.com/pics_artgame/75347539.jpg",
      ],
      [
        "Majespecter",
        "https://storage.googleapis.com/ygoprodeck.com/pics_artgame/31178212.jpg",
      ],
      [
        "Majestic",
        "https://storage.googleapis.com/ygoprodeck.com/pics_artgame/32918479.jpg",
      ],
      [
        "Malefic",
        "https://storage.googleapis.com/ygoprodeck.com/pics_artgame/8310162.jpg",
      ],
      [
        "Malicevorous",
        "https://storage.googleapis.com/ygoprodeck.com/pics_artgame/61791132.jpg",
      ],
      [
        "Marincess",
        "https://storage.googleapis.com/ygoprodeck.com/pics_artgame/47910940.jpg",
      ],
      [
        "Mask",
        "https://storage.googleapis.com/ygoprodeck.com/pics_artgame/29549364.jpg",
      ],
      [
        "Masked HERO",
        "https://storage.googleapis.com/ygoprodeck.com/pics_artgame/58481572.jpg",
      ],
      [
        "Materiactor",
        "https://storage.googleapis.com/ygoprodeck.com/pics_artgame/70597485.jpg",
      ],
      [
        "Mathmech",
        "https://storage.googleapis.com/ygoprodeck.com/pics_artgame/42632209.jpg",
      ],
      [
        "Mayakashi",
        "https://storage.googleapis.com/ygoprodeck.com/pics_artgame/39475024.jpg",
      ],
      [
        "Mecha Phantom Beast",
        "https://storage.googleapis.com/ygoprodeck.com/pics_artgame/67922702.jpg",
      ],
      [
        "Megalith",
        "https://storage.googleapis.com/ygoprodeck.com/pics_artgame/78990927.jpg",
      ],
      [
        "Mekk-Knight",
        "https://storage.googleapis.com/ygoprodeck.com/pics_artgame/28692962.jpg",
      ],
      [
        "Meklord",
        "https://storage.googleapis.com/ygoprodeck.com/pics_artgame/39648965.jpg",
      ],
      [
        "Melffy",
        "https://storage.googleapis.com/ygoprodeck.com/pics_artgame/53054164.jpg",
      ],
      [
        "Melodious",
        "https://storage.googleapis.com/ygoprodeck.com/pics_artgame/34974462.jpg",
      ],
      [
        "Mermail",
        "https://storage.googleapis.com/ygoprodeck.com/pics_artgame/23545031.jpg",
      ],
      [
        "Metalfoes",
        "https://storage.googleapis.com/ygoprodeck.com/pics_artgame/39564736.jpg",
      ],
      [
        "Metaphys",
        "https://storage.googleapis.com/ygoprodeck.com/pics_artgame/45148985.jpg",
      ],
      [
        "Mist Valley",
        "https://storage.googleapis.com/ygoprodeck.com/pics_artgame/29587993.jpg",
      ],
      [
        "Mokey Mokey",
        "https://storage.googleapis.com/ygoprodeck.com/pics_artgame/99910751.jpg",
      ],
      [
        "Monarch",
        "https://storage.googleapis.com/ygoprodeck.com/pics_artgame/23064604.jpg",
      ],
      [
        "Morphtronic",
        "https://storage.googleapis.com/ygoprodeck.com/pics_artgame/28124263.jpg",
      ],
      [
        "Mysterune",
        "https://storage.googleapis.com/ygoprodeck.com/pics_artgame/28373620.jpg",
      ],
      [
        "Myutant",
        "https://storage.googleapis.com/ygoprodeck.com/pics_artgame/6182103.jpg",
      ],
    ],
  },
  {
    letter: "N",
    archetype: [
      [
        "Naturia",
        "https://storage.googleapis.com/ygoprodeck.com/pics_artgame/2956282.jpg",
      ],
      [
        "Nekroz",
        "https://storage.googleapis.com/ygoprodeck.com/pics_artgame/52068432.jpg",
      ],
      [
        "Neo-Spacian",
        "https://storage.googleapis.com/ygoprodeck.com/pics_artgame/17955766.jpg",
      ],
      [
        "Nemeses",
        "https://storage.googleapis.com/ygoprodeck.com/pics_artgame/6728559.jpg",
      ],
      [
        "Nephthys",
        "https://storage.googleapis.com/ygoprodeck.com/pics_artgame/24175232.jpg",
      ],
      [
        "Nimble",
        "https://storage.googleapis.com/ygoprodeck.com/pics_artgame/68353324.jpg",
      ],
      [
        "Ninja",
        "https://storage.googleapis.com/ygoprodeck.com/pics_artgame/82944432.jpg",
      ],
      [
        "Noble Knight",
        "https://storage.googleapis.com/ygoprodeck.com/pics_artgame/42472002.jpg",
      ],
      [
        "Nordic",
        "https://storage.googleapis.com/ygoprodeck.com/pics_artgame/64203620.jpg",
      ],
      [
        "Numeron",
        "https://storage.googleapis.com/ygoprodeck.com/pics_artgame/15232745.jpg",
      ],
    ],
  },
  {
    letter: "O",
    archetype: [
      [
        "Odd-Eyes",
        "https://storage.googleapis.com/ygoprodeck.com/pics_artgame/16178681.jpg",
      ],
      [
        "Ogdoadic",
        "https://storage.googleapis.com/ygoprodeck.com/pics_artgame/61160289.jpg",
      ],
      [
        "Ojama",
        "https://storage.googleapis.com/ygoprodeck.com/pics_artgame/42941100.jpg",
      ],
      [
        "Orcust",
        "https://storage.googleapis.com/ygoprodeck.com/pics_artgame/93854893.jpg",
      ],
    ],
  },
  {
    letter: "P",
    archetype: [
      [
        "P.U.N.K.",
        "https://storage.googleapis.com/ygoprodeck.com/pics_artgame/44708154.jpg",
      ],
      [
        "Paleozoic",
        "https://storage.googleapis.com/ygoprodeck.com/pics_artgame/37649320.jpg",
      ],
      [
        "Parshath",
        "https://storage.googleapis.com/ygoprodeck.com/pics_artgame/18036057.jpg",
      ],
      [
        "Parsite",
        "https://storage.googleapis.com/ygoprodeck.com/pics_artgame/7369217.jpg",
      ],
      [
        "Pendulum",
        "https://storage.googleapis.com/ygoprodeck.com/pics_artgame/22125101.jpg",
      ],
      [
        "Penguin",
        "https://storage.googleapis.com/ygoprodeck.com/pics_artgame/91397409.jpg",
      ],
      [
        "Performage",
        "https://storage.googleapis.com/ygoprodeck.com/pics_artgame/68819554.jpg",
      ],
      [
        "Performapal",
        "https://storage.googleapis.com/ygoprodeck.com/pics_artgame/37745740.jpg",
      ],
      [
        "Phantasm Spiral",
        "https://storage.googleapis.com/ygoprodeck.com/pics_artgame/2819436.jpg",
      ],
      [
        "Phantom Beast",
        "https://storage.googleapis.com/ygoprodeck.com/pics_artgame/7576264.jpg",
      ],
      [
        "Phantom Knights",
        "https://storage.googleapis.com/ygoprodeck.com/pics_artgame/25538345.jpg",
      ],

      [
        "Photon",
        "https://storage.googleapis.com/ygoprodeck.com/pics_artgame/89132148.jpg",
      ],
      [
        "Plunder Patroll",
        "https://storage.googleapis.com/ygoprodeck.com/pics_artgame/16178681.jpg",
      ],
      [
        "Prank-Kids",
        "https://storage.googleapis.com/ygoprodeck.com/pics_artgame/81997228.jpg",
      ],
      [
        "Predaplant",
        "https://storage.googleapis.com/ygoprodeck.com/pics_artgame/66309175.jpg",
      ],
      [
        "Prediction Princess",
        "https://storage.googleapis.com/ygoprodeck.com/pics_artgame/94997874.jpg",
      ],
      [
        "PSY-Frame",
        "https://storage.googleapis.com/ygoprodeck.com/pics_artgame/38814750.jpg",
      ],
      [
        "Psychic",
        "https://storage.googleapis.com/ygoprodeck.com/pics_artgame/95526884.jpg",
      ],
    ],
  },
  {
    letter: "Q",
    archetype: [
      [
        "Qli",
        "https://storage.googleapis.com/ygoprodeck.com/pics_artgame/20426907.jpg",
      ],
    ],
  },
  {
    letter: "R",
    archetype: [
      [
        "Raidraptor",
        "https://storage.googleapis.com/ygoprodeck.com/pics_artgame/96157835.jpg",
      ],
      [
        "Rank-Up-Magic",
        "https://storage.googleapis.com/ygoprodeck.com/pics_artgame/67517351.jpg",
      ],
      [
        "Red-Eyes",
        "https://storage.googleapis.com/ygoprodeck.com/pics_artgame/74677422.jpg",
      ],
      [
        "Reptilianne",
        "https://storage.googleapis.com/ygoprodeck.com/pics_artgame/16886617.jpg",
      ],
      [
        "Resonator",
        "https://storage.googleapis.com/ygoprodeck.com/pics_artgame/97021916.jpg",
      ],
      [
        "Rikka",
        "https://storage.googleapis.com/ygoprodeck.com/pics_artgame/33491462.jpg",
      ],
      [
        "Ritual Beast",
        "https://storage.googleapis.com/ygoprodeck.com/pics_artgame/86274272.jpg",
      ],
      [
        "Roid",
        "https://storage.googleapis.com/ygoprodeck.com/pics_artgame/98927491.jpg",
      ],
      [
        "Rokket",
        "https://storage.googleapis.com/ygoprodeck.com/pics_artgame/32472237.jpg",
      ],
      [
        "Rose Dragon",
        "https://storage.googleapis.com/ygoprodeck.com/pics_artgame/73580471.jpg",
      ],
    ],
  },

  {
    letter: "S",
    archetype: [
      [
        "S-Force",
        "https://storage.googleapis.com/ygoprodeck.com/pics_artgame/35334193.jpg",
      ],
      [
        "Sacred Beast",
        "https://storage.googleapis.com/ygoprodeck.com/pics_artgame/69890967.jpg",
      ],
      [
        "Salamangreat",
        "https://storage.googleapis.com/ygoprodeck.com/pics_artgame/60303245.jpg",
      ],
      [
        "Scareclaw",
        "https://storage.googleapis.com/ygoprodeck.com/pics_artgame/82361809.jpg",
      ],
      [
        "Scrap",
        "https://storage.googleapis.com/ygoprodeck.com/pics_artgame/50278554.jpg",
      ],
      [
        "Shaddoll",
        "https://storage.googleapis.com/ygoprodeck.com/pics_artgame/20366274.jpg",
      ],
      [
        "Shark",
        "https://storage.googleapis.com/ygoprodeck.com/pics_artgame/10532969.jpg",
      ],
      [
        "Shinobird",
        "https://storage.googleapis.com/ygoprodeck.com/pics_artgame/66815913.jpg",
      ],
      [
        "Simorgh",
        "https://storage.googleapis.com/ygoprodeck.com/pics_artgame/86489182.jpg",
      ],
      [
        "Shiranui",
        "https://storage.googleapis.com/ygoprodeck.com/pics_artgame/10028504.jpg",
      ],
      [
        "Silent Magician",
        "https://storage.googleapis.com/ygoprodeck.com/pics_artgame/41175645.jpg",
      ],
      [
        "Silent Swordsman",
        "https://storage.googleapis.com/ygoprodeck.com/pics_artgame/15180041.jpg",
      ],
      [
        "Six Samurai",
        "https://storage.googleapis.com/ygoprodeck.com/pics_artgame/74752631.jpg",
      ],
      [
        "Skull Servant",
        "https://storage.googleapis.com/ygoprodeck.com/pics_artgame/36021814.jpg",
      ],
      [
        "Sky Striker",
        "https://storage.googleapis.com/ygoprodeck.com/pics_artgame/8491308.jpg",
      ],
      [
        "Slime",
        "https://storage.googleapis.com/ygoprodeck.com/pics_artgame/18914778.jpg",
      ],
      [
        "Solfachord",
        "https://storage.googleapis.com/ygoprodeck.com/pics_artgame/29650040.jpg",
      ],
      [
        "Stigmatika",
        "https://storage.googleapis.com/ygoprodeck.com/pics_artgame/34995106.jpg",
      ],
      [
        "Swordsoul",
        "https://storage.googleapis.com/ygoprodeck.com/pics_artgame/20001443.jpg",
      ],
      [
        "Speedroid",
        "https://storage.googleapis.com/ygoprodeck.com/pics_artgame/81275020.jpg",
      ],
      [
        "Spellbook",
        "https://storage.googleapis.com/ygoprodeck.com/pics_artgame/61592395.jpg",
      ],
      [
        "Splight",
        "https://storage.googleapis.com/ygoprodeck.com/pics_artgame/54498517.jpg",
      ],
      [
        "Springan",
        "https://storage.googleapis.com/ygoprodeck.com/pics_artgame/29601381.jpg",
      ],
      [
        "Spyral",
        "https://storage.googleapis.com/ygoprodeck.com/pics_artgame/1322368.jpg",
      ],
      [
        "Star Seraph",
        "https://storage.googleapis.com/ygoprodeck.com/pics_artgame/38331564.jpg",
      ],
      [
        "Starry Knight",
        "https://storage.googleapis.com/ygoprodeck.com/pics_artgame/27036706.jpg",
      ],
      [
        "Steelswarm",
        "https://storage.googleapis.com/ygoprodeck.com/pics_artgame/94092230.jpg",
      ],
      [
        "Subterror",
        "https://storage.googleapis.com/ygoprodeck.com/pics_artgame/42713844.jpg",
      ],
      [
        "Sunavalon",
        "https://storage.googleapis.com/ygoprodeck.com/pics_artgame/39880350.jpg",
      ],
      [
        "Super Defense Robot",
        "https://storage.googleapis.com/ygoprodeck.com/pics_artgame/45496268.jpg",
      ],
      [
        "Superheavy Samurai",
        "https://storage.googleapis.com/ygoprodeck.com/pics_artgame/3117804.jpg",
      ],
      [
        "Super Quant",
        "https://storage.googleapis.com/ygoprodeck.com/pics_artgame/72332074.jpg",
      ],
      [
        "Supreme King",
        "https://storage.googleapis.com/ygoprodeck.com/pics_artgame/92428405.jpg",
      ],
      [
        "Sylvan",
        "https://storage.googleapis.com/ygoprodeck.com/pics_artgame/10406322.jpg",
      ],
      [
        "Symphonic Warrior",
        "https://storage.googleapis.com/ygoprodeck.com/pics_artgame/68933343.jpg",
      ],
      [
        "Synchron",
        "https://storage.googleapis.com/ygoprodeck.com/pics_artgame/37675907.jpg",
      ],
    ],
  },
  {
    letter: "T",
    archetype: [
      [
        "T.G.",
        "https://storage.googleapis.com/ygoprodeck.com/pics_artgame/51447164.jpg",
      ],
      [
        "Tearalaments.",
        "https://storage.googleapis.com/ygoprodeck.com/pics_artgame/92731385.jpg",
      ],
      [
        "Tellarknight",
        "https://storage.googleapis.com/ygoprodeck.com/pics_artgame/64414267.jpg",
      ],
      [
        "Tenyi",
        "https://storage.googleapis.com/ygoprodeck.com/pics_artgame/5402805.jpg",
      ],

      [
        "The Agent",
        "https://storage.googleapis.com/ygoprodeck.com/pics_artgame/90290572.jpg",
      ],
      [
        "Time Thief",
        "https://storage.googleapis.com/ygoprodeck.com/pics_artgame/55285840.jpg",
      ],
      [
        "The Weather",
        "https://storage.googleapis.com/ygoprodeck.com/pics_artgame/54178659.jpg",
      ],
      [
        "Therions",
        "https://storage.googleapis.com/ygoprodeck.com/pics_artgame/75290703.jpg",
      ],
      [
        "Thunder Dragon",
        "https://storage.googleapis.com/ygoprodeck.com/pics_artgame/15291624.jpg",
      ],
      [
        "Timelord",
        "https://storage.googleapis.com/ygoprodeck.com/pics_artgame/6616912.jpg",
      ],
      [
        "Tindangle",
        "https://storage.googleapis.com/ygoprodeck.com/pics_artgame/75119040.jpg",
      ],
      [
        "Toon",
        "https://storage.googleapis.com/ygoprodeck.com/pics_artgame/15259704.jpg",
      ],
      [
        "Train",
        "https://storage.googleapis.com/ygoprodeck.com/pics_artgame/52481437.jpg",
      ],
      [
        "Traptrix",
        "https://storage.googleapis.com/ygoprodeck.com/pics_artgame/6511113.jpg",
      ],
      [
        "Triamid",
        "https://storage.googleapis.com/ygoprodeck.com/pics_artgame/68406755.jpg",
      ],
      [
        "Tri-Brigade",
        "https://storage.googleapis.com/ygoprodeck.com/pics_artgame/99726621.jpg",
      ],
      [
        "Trickstar",
        "https://storage.googleapis.com/ygoprodeck.com/pics_artgame/91272072.jpg",
      ],
      [
        "True Draco",
        "https://storage.googleapis.com/ygoprodeck.com/pics_artgame/35125879.jpg",
      ],
    ],
  },
  {
    letter: "U",
    archetype: [
      [
        "U.A.",
        "https://storage.googleapis.com/ygoprodeck.com/pics_artgame/72491806.jpg",
      ],
      [
        "Unmbral Horror",
        "https://storage.googleapis.com/ygoprodeck.com/pics_artgame/49456901.jpg",
      ],
      [
        "Unchained",
        "https://storage.googleapis.com/ygoprodeck.com/pics_artgame/29479265.jpg",
      ],

      [
        "Ursarctic",
        "https://storage.googleapis.com/ygoprodeck.com/pics_artgame/80086070.jpg",
      ],
      [
        "Utopia",
        "https://storage.googleapis.com/ygoprodeck.com/pics_artgame/84013238.jpg",
      ],
      [
        "Umi",
        "https://storage.googleapis.com/ygoprodeck.com/pics_artgame/295517.jpg",
      ],
    ],
  },
  {
    letter: "V",
    archetype: [
      [
        "Valkyrie",
        "https://storage.googleapis.com/ygoprodeck.com/pics_artgame/83705073.jpg",
      ],
      [
        "Vampire",
        "https://storage.googleapis.com/ygoprodeck.com/pics_artgame/38250531.jpg",
      ],
      [
        "Vassal",
        "https://storage.googleapis.com/ygoprodeck.com/pics_artgame/22404675.jpg",
      ],
      [
        "Vendread",
        "https://storage.googleapis.com/ygoprodeck.com/pics_artgame/91420202.jpg",
      ],
      [
        "Venom",
        "https://storage.googleapis.com/ygoprodeck.com/pics_artgame/8062132.jpg",
      ],
      [
        "Virtual World",
        "https://storage.googleapis.com/ygoprodeck.com/pics_artgame/92519087.jpg",
      ],
      [
        "Vision HERO",
        "https://storage.googleapis.com/ygoprodeck.com/pics_artgame/45170821.jpg",
      ],
      [
        "Volcanic",
        "https://storage.googleapis.com/ygoprodeck.com/pics_artgame/32543380.jpg",
      ],
      [
        "Vylon",
        "https://storage.googleapis.com/ygoprodeck.com/pics_artgame/93157004.jpg",
      ],
    ],
  },
  {
    letter: "W",
    archetype: [
      [
        "War Rock",
        "https://storage.googleapis.com/ygoprodeck.com/pics_artgame/10497636.jpg",
      ],
      [
        "Watt",
        "https://storage.googleapis.com/ygoprodeck.com/pics_artgame/2772236.jpg",
      ],
      [
        "Wind-up",
        "https://storage.googleapis.com/ygoprodeck.com/pics_artgame/77334267.jpg",
      ],
      [
        "Windwitch",
        "https://storage.googleapis.com/ygoprodeck.com/pics_artgame/43722862.jpg",
      ],
      [
        "Witchcrafter",
        "https://storage.googleapis.com/ygoprodeck.com/pics_artgame/9603252.jpg",
      ],
      [
        "World Chalice",
        "https://storage.googleapis.com/ygoprodeck.com/pics_artgame/58400390.jpg",
      ],
      [
        "World Legacy",
        "https://storage.googleapis.com/ygoprodeck.com/pics_artgame/57288708.jpg",
      ],
      [
        "Worm",
        "https://storage.googleapis.com/ygoprodeck.com/pics_artgame/10026986.jpg",
      ],
    ],
  },
  {
    letter: "X",
    archetype: [
      [
        "X-Saber",
        "https://storage.googleapis.com/ygoprodeck.com/pics_artgame/52352005.jpg",
      ],
    ],
  },
  {
    letter: "Y",
    archetype: [
      [
        "Yang Zing",
        "https://storage.googleapis.com/ygoprodeck.com/pics_artgame/83755611.jpg",
      ],
      [
        "Yosenju",
        "https://cdn.discordapp.com/attachments/747928182891610213/988674588756045834/daibak.webp",
      ],
      [
        "Yubel",
        "https://storage.googleapis.com/ygoprodeck.com/pics_artgame/78371393.jpg",
      ],
    ],
  },
  {
    letter: "Z",
    archetype: [
      [
        "Zefra",
        "https://storage.googleapis.com/ygoprodeck.com/pics_artgame/32354768.jpg",
      ],
      [
        "ZEXAL",
        "https://storage.googleapis.com/ygoprodeck.com/pics_artgame/32164201.jpg",
      ],
      [
        "Zoodiac",
        "https://storage.googleapis.com/ygoprodeck.com/pics_artgame/48905153.jpg",
      ],
    ],
  },
];
export const urls = [
  "Albaz%20New",
  "Abyss%20Actor",
  "Adamancipator",
  "Adventurer%20Token",
  "Aesir",
  "Agent",
  "Alien",
  "Ally%20of%20Justice",
  "Altergeist",
  "Amazemment",
  "Amazoness",
  "Amorphage",
  "Ancient%20Gear",
  "Ancient%20Warriors",
  "Appliancer",
  "Aquaactress",
  "Arcana%20Force",
  "Archfiend",
  "Armed%20Dragon",
  "Aromage",
  "Artifact",
  "Assault%20Mode",
  "Atlantean",
  "A-to-Z",
  "Batteryman",
  "Battlewasp",
  "Battlin%20Boxer",
  "Beetrooper",
  "Black%20Luster",
  "Blackwing",
  "Blue-Eyes",
  "Bounzer",
  "Bujin",
  "Burning%20Abyss",
  "Buster%20Blader",
  "Butterspy",
  "Chaos",
  "Chemicritter",
  "Chronomaly",
  "Chrysalis",
  "Cipher",
  "Cloudian",
  "Code%20Talker",
  "Constellar",
  "Crusadia",
  "Crystal%20Beast",
  "Crystron",
  "Cubic",
  "Cyber",
  "Cyberdark",
  "Cyber%20Dragon",
  "D/D/",
  "Danger!",
  "Darklord",
  "Dark%20Magician",
  "Dark%20Scorpion",
  "Dark%20World",
  "D.D.",
  "Deep%20Sea",
  "Deskbot",
  "Despia",
  "Destiny%20Hero",
  "Digital%20Bug",
  "Dinomist",
  "Dinomorphia",
  "Dinowrestler",
  "Dododo",
  "Dogmatika",
  "Dracoslayer",
  "Dragon%20Ruler",
  "Dragonmaid",
  "Dragunity",
  "Dream%20Mirror",
  "Drytron",
  "Dual%20Avatar",
  "Duston",
  "Earthbound%20Immortal",
  "Edge%20Imp",
  "Edlich",
  "Elemental%20Hero",
  "Elementsaber",
  "Empowered%20Warrior",
  "Endymion",
  "Evil%20Eye",
  "Evil%20Hero",
  "Evilswarm",
  "Evoltile",
  "Exosister",
  "Fabled",
  "Face%20Cards",
  "F.A.",
  "Fairy%20Tail",
  "Familiar-Possessed",
  "Brotherhood%20of%20the%20Fire%20Fist",
  "Fire%20King",
  "Flamvell",
  "Fleur",
  "Floowandereeze",
  "Flower%20Cardian",
  "Fluffal",
  "Fortune%20Fairy",
  "Fortune%20Lady",
  "Fossil%20Fusion",
  "Frightfur",
  "Frog",
  "Fur%20Hire",
  "Gadget",
  "Gagaga",
  "Gaia",
  "Galaxy",
  "Ganbara",
  "Geargia",
  "Gem-",
  "Generaider",
  "Genex",
  "Ghostrick",
  "Gimmick%20Puppet",
  "Gishki",
  "Glacial%20Beast",
  "Gladiator%20Beast",
  "Goblin",
  "Gogogo",
  "Gorgonic",
  "Gouki",
  "Goyo",
  "Gravekeeper",
  "Graydle",
  "Gunkan",
  "Gusto",
  "Harpie",
  "Hazy%20Flame",
  "Heraldic%20Beast",
  "Heroic",
  "Hieratic",
  "Ice%20Barrier",
  "Icejade",
  "Igknight",
  "Ignister",
  "Impcantation",
  "Infernity",
  "Infernoid",
  "Infinitrack",
  "Invoked",
  "Inzektor",
  "Iron%20Chain",
  "Junk",
  "Jurrac",
  "Kaiju",
  "Karakuri",
  "Knightmare",
  "Koa'ki%20Meiru",
  "Kozmo",
  "Krawler",
  "Kuriboh",
  "Laval",
  "Libromancer",
  "Lightray",
  "Lightsworn",
  "Lswarm",
  "Lunalight",
  "Lyrilusc",
  "Machina",
  "Madolche",
  "Magical%20Musket",
  "Magician",
  "Magikey",
  "Magistus",
  "Majespecter",
  "Malefic",
  "Marincess",
  "Masked%20HERO",
  "Mathmech",
  "Mayakashi",
  "Mecha%20Phantom%20Beast",
  "Megalith",
  "Mekk-Knight",
  "Meklord",
  "Melffy",
  "Melodious",
  "Mermail",
  "Metalfoes",
  "Metaphys",
  "Mist%20Valley",
  "Monarch",
  "Morphtronic",
  "Mystical%20Beast",
  "Mythical%20Beast",
  "Myutant",
  "Naturia",
  "Nekroz",
  "Neo-Spacian",
  "Neos",
  "Nemeses",
  "Nephthys",
  "Ninja",
  "Noble%20Knight",
  "Nordic",
  "Number",
  "Numeron",
  "Odd-Eyes",
  "Ogdoadic",
  "Orcust",
  "Ojama",
  "P.U.N.K.",
  "Paleozoic",
  "Parshath",
  "Penguin",
  "Performage",
  "Performapal",
  "Phantasm%20Spiral",
  "Phantom%20Beast",
  "Photon",
  "Plunder%20Patroll",
  "Prank-Kids",
  "Predaplant",
  "Prediction%20Princess",
  "PSY-Framegear",
  "Psychic",
  "Qli",
  "Raidraptor",
  "Red-Eyes",
  "Reptilianne",
  "Resonator",
  "Rikka",
  "Risebell",
  "Ritual%20Beast",
  "Roid",
  "Rokket",
  "Rose",
  "S-Force",
  "Salamangreat",
  "Scareclaw",
  "Scrap",
  "Shaddoll",
  "Shark",
  "Shinobird",
  "Simorgh",
  "Shiranui",
  "Silent%20Magician",
  "Silent%20Swordsman",
  "Six%20Samurai",
  "Skull%20Servant",
  "Sky%20Striker",
  "Solfachord",
  "Swordsoul",
  "Speedroid",
  "Spellbook",
  "Springan",
  "Spyral",
  "Spellcaster",
  "Star%20Sereph",
  "Starry%20Knight",
  "Steelswarm",
  "Subterror",
  "Sunavalon",
  "Superheavy%20Samurai",
  "Supreme%20King",
  "Sylvan",
  "Symphonic%20Warrior",
  "Synchron",
  "tellarknight",
  "Tenyi",
  "T.G.",
  "The%20Agent",
  "Time%20Thief",
  "The%20Phantom%20Knights",
  "The%20Weather",
  "Therion",
  "Thunder%20Dragon",
  "Timelord",
  "Tindangle",
  "Toon",
  "Traptrix",
  "Triamid",
  "Tri-Brigade",
  "Trickstar",
  "True%20King",
  "Twilightsworn",
  "U.A.",
  "Unchained",
  "Ursarctic",
  "Utopia",
  "Vampire",
  "Vassal",
  "Vendread",
  "Venom",
  "Virtual%20World",
  "Vision%20HERO",
  "Volcanic",
  "Vylon",
  "War%20Rock",
  "Watt",
  "Wind-up",
  "Windwitch",
  "Witchcrafter",
  "World%20Chalice",
  "World%20Legacy",
  "Worm",
  "Xtra%20HERO",
  "X-Saber",
  "Yang%20Zing",
  "Yosenju",
  "Zefra",
  "Zombie",
  "Zoodiac",
  "Zubaba",
  "ZW%20-",
];
